### ISSUE TITLE
Migrate to Qiskit 1.0

### ISSUE THREAD

**Issue by frankharkins** [iqm-finland/qiskit-on-iqm#107]
I'm making this issue because this project is part of the [Qiskit ecosystem](https://qiskit.github.io/ecosystem/).

We're introducing a requirement that all projects are compatible with Qiskit 1.0. New users will be using Qiskit 1.0 and we want to make sure any projects we guide them to work straight away.

See our [migration guide](https://docs.quantum.ibm.com/api/migration-guides) and let me know if you need any support (such as answering questions about Qiskit or code review). With Qiskit's new stability policy, this should be the last change needed for a while. We do value your project so let me know if you need any help migrating or have any other concerns.

**Comment by Aerylia** [comment]
To make a start with the migration. We have created a quick work around for users who are willing to install the project from source on  [the branch: Qiskit-hack](https://github.com/iqm-finland/qiskit-on-iqm/tree/qiskit-hack). Simply download the source code from this branch and install it by running 
`pip install .`
from the downloaded folder in the command line if you have python installed.

We will need a bit more time to make sure that everything works as expected. And to implement the features that will remove the depreciation warnings. Early users from the branch can report their issues as comments on this issue.
Thank you for your patience.
