### ISSUE TITLE
id gate cannot be expanded when compiled for target

### ISSUE THREAD

**Issue by manzanillo** [iqm-finland/qiskit-on-iqm#46]
If I use a circuit with an Identity gate the transpile rules don't know how to handle it as it says in the docs the gate "should not be optimized or unrolled (it is an opaque gate)". (https://qiskit.org/documentation/stubs/qiskit.circuit.library.IGate.html)

Minimal example to reporduce:
```
from qiskit import execute, QuantumCircuit
from qiskit_iqm import IQMFakeAdonis

circuit = QuantumCircuit(2)
circuit.i(q)
circuit.measure_all()

backend = IQMFakeAdonis()
job = execute(circuit, backend, shots=1000)
job.result().get_counts()
```
Output:
```
QiskitError: "Cannot unroll the circuit to the given basis, ['r', 'cz', 'measure']. Instruction id not found in equivalence library and no rule found to expand."
```

One solution would be to add identity gate to the basis.

**Comment by freetonik** [comment]
We've taken this into consideration and will process at some point. Thanks!
